<?php

namespace RecurlyClient\Entity;

class BillingInfoToken extends \RecurlyClient\Entity\EntityAbstract
{
    /**
     * A token generated by Recurly.js.
     *
     * @var string
     */
    protected $token_id;

    /**
     * {@inheritdoc}
     */
    public function name()
    {
        return 'billing_info';
    }

    /**
     * Gets the value of token_id.
     *
     * @return string
     */
    public function getTokenId()
    {
        return $this->token_id;
    }

    /**
     * Sets the value of token_id.
     *
     * @param string $token_id the token id
     *
     * @return self
     */
    public function setTokenId($token_id)
    {
        $this->token_id = $token_id;

        return $this;
    }
}
